### ISSUE TITLE
Critical security vulnerabilities

### ISSUE THREAD

**Issue by maqp** [seripap/darkwire.io#1]
I'm not an expert on JS but it is the case of every programming language, that Math.random() is not a cryptographically secure pseudorandom number generator (CSPRNG). 

[Your encryption key generator is completely insecure](https://github.com/seripap/darkwire.io/blob/master/src/js/main.js#L539).

Once that's fixed, the charset you're using is missing the 'm' and the length is only 16 chars. The current encryption keys have theoretical maximum strength of 61^16 = 94 bits. This is not enough; While it's secure against many crackers, it's not secure against nation states that break crypto. Ensure that the length of key generated by a CSPRNG is at least 43.

**Comment by seripap** [comment]
Good call. Switching to [RFC4122](http://www.ietf.org/rfc/rfc4122.txt) UUIDS.

**Comment by maqp** [comment]
I'm not entirely sure the issue is fixed. Your code is now using [uuid.v4()](https://github.com/seripap/darkwire.io/blob/master/src/js/main.js#L535).

It is said [here](http://blog.tompawlak.org/generate-random-values-nodejs-javascript) that uuidv4 also uses math.random(). 

Please consider using [crypto.randomBytes](https://nodejs.org/api/crypto.html#crypto_crypto_randombytes_size_callback).

**Comment by seripap** [comment]
The key generation is ran on the client side so we do not have access to the node api without exposing the method. We do not want to transmit the generated passphrase to the server at any point- whether that is creating the key or receiving the key.

The actually uuid.v4 method uses [window.crypto.getRandomValues](https://github.com/seripap/darkwire.io/blob/master/src/public/vendor/uuid.js#L24-L27) and only [falls back to math.random](https://github.com/seripap/darkwire.io/blob/master/src/public/vendor/uuid.js#L38-L43) if the client does not support the crypto api.

For v1.1.0 release- we are in works of disabling client browsers who do not support the crypto method.

**Comment by alanfriedman** [comment]
See [this commit](https://github.com/seripap/darkwire.io/commit/39e4d3d56c41c0aaa3a4bf477463c96b28fcf8c3) for new updates.

We now use the [Crypto web API](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) to handle key generation, encryption and decryption. Browsers that don't support this API are prevented from using the app.
