### ISSUE TITLE
enhancement: support `/me` switch

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#12]
Here another nice function from IRC. Using the /me switch one can express things like 

> `/me really would like this feature` 

as 

> **@dietmarw*** really would like this feature

Not important but nice to have.

**Comment by seripap** [comment]
This is actually part of the initial work effort when I started building slash command support. Should be baked :+1:

**Comment by dietmarw** [comment]
Sorry but it does not work as expected. It does now do the same as `/nick` but what it should do is display the current nick simply in boldface and with star at the end.

**Comment by seripap** [comment]
More or less styling- I just opted with the asterisk to be the prefix versus following the username. The functionality is there, we can always look into restyling it before we release :+1: 
![screenshot 2016-02-24 09 41 43](https://cloud.githubusercontent.com/assets/683200/13288791/75ab5a82-dadb-11e5-9569-8e54f2b9e38f.png)

**Comment by dietmarw** [comment]
How strange. I'm on edfab8a0c337b7ba1fb890188f64470675bb9aa6 and just did once again:
```
npm install
npm start
```

Anything else I should do to test the current version?

**Comment by seripap** [comment]
try
```
gulp bundle
npm start
```

We'll finalize how to build the source correctly after we fix our testing framework

**Comment by dietmarw** [comment]
Ha you beat me to it. Was just saying that I ran a total clean up and a gulp bundle in addition :-)
Thanks. Now it works as expected.

**Comment by dietmarw** [comment]
Would it be possible to use the nick colour for the line instead of green for all who use `/me ...`?
