### ISSUE TITLE
Heroku deployment

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#15]
I tried deploying darkwire.io on [Heroku](https://heroku.com) but it seems the gulp setup is conflicting. I don't know if you haver tried it with Heroku but given that you can one instance of a node.js application for free it makes a great test system for the newest features if one doesn't just want to test locally.

If there is interest in making it runnable on Heroku I can provide some logs. I was hoping to be able to fix it myself and send you a PR. But it seems my node.js foo is just too pathetic for that.

**Comment by alanfriedman** [comment]
I've used Heroku for other things. What error are you getting? 

You might need to reference gulp locally. So in your Procfile try `web: npm run bundle && node_modules/gulp/bin/gulp.js start `

**Comment by alanfriedman** [comment]
Actually, in production you probably shouldn't be using Nodemon to run the app. Try just `web: npm run bundle && node index.js`

**Comment by dietmarw** [comment]
I tried your suggestion. Install is successful but the app crashes: https://gist.github.com/dietmarw/1cfe1b871c9d0d60f69d

**Comment by alanfriedman** [comment]
I'm guessing Gulp isn't installed globally on Heroku. So try `node_modules/gulp/bin/gulp.js bundle && node index.js`

**Comment by dietmarw** [comment]
One step further: https://gist.github.com/dietmarw/1cfe1b871c9d0d60f69d

**Comment by alanfriedman** [comment]
What branch are you on? Do you have a `.babelrc` file in the root? Should look like this:

    {
      "presets": ["es2015"]
    }

**Comment by dietmarw** [comment]
I'm on feature/Filetransfer and yes that file is there.

**Comment by alanfriedman** [comment]
Looks like it's having trouble finding that file. You can try something like [this](http://stackoverflow.com/questions/33891286/failed-to-use-gulp-and-babel-transpile-javascript-file) where you import the preset directly into Gulp.

Weird that it says 'relative to directory "/app"' - I guess /app is the root directory Heroku makes?

**Comment by dietmarw** [comment]
Yes "/app" is the directory heroku deploys from (so copies all the files to). I tried adding the solution you linked to into the gulpfile.babel.js but got exactly the same error message. So this did not help :frowning:

**Comment by alanfriedman** [comment]
So our build process/dependencies are kind of a mess right now - so this will be sorted out - but I think the problem is that Heroku [doesn't install devDependencies](https://devcenter.heroku.com/articles/nodejs-support#customizing-the-build-process). 

You can either move babel and other `devDependencies` in `package.json` into `dependencies` or run `heroku config:set NPM_CONFIG_PRODUCTION=false`

**Comment by dietmarw** [comment]
OK that brought it a good bit  further. So to summarise, with:

 * `Procfile` : `web: npm run bundle && node_modules/gulp/bin/gulp.js start`
 * `heroku config:set NPM_CONFIG_PRODUCTION=false`

Heroku manages to start the app now. It will timeout though because it can not bind the port 3000. Herokuapps normally take 5000. I think to have seen a commit one place where you can configure this in darkwire too now. Any pointers?

**Comment by seripap** [comment]
```port=5000 npm start```

**Comment by alanfriedman** [comment]
`npm run bundle && port=5000 node_modules/gulp/bin/gulp.js start`

I wouldn't recommend using `nodemon` in production (which is what `gulp start` uses). I would use this: `node_modules/gulp/bin/gulp.js bundle && port=5000 node index.js`

**Comment by seripap** [comment]
I would also advise not using feature branches as they are just for development and changes rapidly. Stick with develop for an edge version and master for a stable release :+1:

**Comment by dietmarw** [comment]
Well sure. But the whole point here is being able to test things out and give early feedback. :-) It works fine on my local install and just thought it would be fun to have a through away heroku test instance.

**Comment by dietmarw** [comment]
Anyway it seems I found two pointers for a possible solution of the last remaining issue: `Error R10 (Boot timeout) -> Web process failed to bind to $PORT within 60 seconds of launch`. Either:
 * the localhost needs to be addressed as `0.0.0.0` ([GH issue](https://github.com/angular-fullstack/generator-angular-fullstack/issues/1071))

or/and

 * the port listening method needs to be [slightly modified](http://stackoverflow.com/questions/31092538/heroku-node-js-error-r10-boot-timeout-web-process-failed-to-bind-to-port-w)

**Comment by alanfriedman** [comment]
Did you try [this](http://stackoverflow.com/a/15693371/5079258)?

`.listen(process.env.PORT || 5000)`

**Comment by dietmarw** [comment]
I saw that but didn't know where to add that line.

**Comment by seripap** [comment]
Check out [this branch](https://github.com/seripap/darkwire.io/tree/feature/containers). 

Procfile
```
web: npm run bundle && port=$PORT node_modules/gulp/bin/gulp.js start
```

**Comment by dietmarw** [comment]
THAT WORKED! Thanks: http://moleaks.herokuapp.com/4yco8fOjg

Only difference, following @alanfriedman 's advice I used: 
`web: npm run bundle && port=$PORT node index.js`

**Comment by seripap** [comment]
Awesome- from develop, you can use actually replace your Procfile with ```web: port=$PORT npm start``` and it *should* work. Also remember to https! Cheers.

**Comment by dietmarw** [comment]
OK will try that right away. Well though https gives additional "tunnel" the streams themselvs should still be encrypted even if via http, right?

**Comment by seripap** [comment]
Correct- however the app won't work in [latest version of Chrome unless its through https](https://www.chromium.org/Home/chromium-security/prefer-secure-origins-for-powerful-new-features). If you're just deploying for testing on another browser, you should be ok.

**Comment by dietmarw** [comment]
Thanks to the heroku test-setup I can now see that text-input is not working for Chrome browser (linux and windows). Works fine on Firefox. And local install works everywhere. Feel free to test it with the heroku address from above.

**Comment by dietmarw** [comment]
Ah you beat me to it again. So ignore ;-)

**Comment by alanfriedman** [comment]
Also Heroku gives you free SSL on their endpoints. So: https://moleaks.herokuapp.com

**Comment by dietmarw** [comment]
Cool. I was just starting to look into Let's encrypt+Heroku

**Comment by dietmarw** [comment]
Btw, you might wanna register darkwire as herokuapp ;-) At first I've chosen that name but thought it might be confused with the real thing.

**Comment by seripap** [comment]
[darkwire.herokuapp.com](darkwire.herokuapp.com) :+1:

**Comment by alanfriedman** [comment]
SSL cert on Heroku is only needed if you want to use a custom domain.

**Comment by dietmarw** [comment]
You could use the herokuapp as part of CI deploy.
