### ISSUE TITLE
Feature request: /clear command to clear scrollback

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#18]
Would be nice to have this. From IRC: 

` /clear Clears the entire scrollback buffer of the current window.`

Until now I simply used refresh page but since /nick is available this means loosing the handle.

**Comment by seripap** [comment]
#28 will take care of this. This was actually part of our initial thought when we we're releasing this- for CMD+K support. Since slash commands are built in, i've went ahead and added it.

**Comment by seripap** [comment]
Released in v1.5.3 (ed2ab53)
