### ISSUE TITLE
Feature request: custom handles

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#2]
I've just started playing with this service (due to cryptocat becoming more and more unreliable due to outages) and one thing that would be nice to have is being able to rename the handles to make identification of different people easier. I know it will undermine the anonymity somewhat  and you don't have any guarantee that the person is really the one it's saying it is but still would be nice to have.

**Comment by dietmarw** [comment]
Just noticed. It would already help if each random handle get's its own colour.

**Comment by seripap** [comment]
Custom handles is in the pipeline v1.5 (#5). I'll throw some more hex values to the table to randomize it a bit as well.

**Comment by dietmarw** [comment]
Interesting "quirk". Different users can set the same handle. Now at first I thought this is not too bad since I sometimes have one machine just holding the room open whilst chatting on the other machine. Plus the colour is the same of the handles (due to the colour hash algorithm). But problem is that if 2 or more have the same handle then what ever one writes is not send to the other sessions with the same handle. Probably solution is perhaps to not allow rename to already existing handles.
