### ISSUE TITLE
enhancement: make the "... is typing" message optional or improve

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#3]
The `... is typing` message is kind of a nuisance when the screen is full which means each time it appears all the conversation text jumps slightly up and then slightly down again. This is distracting. So it would be nice to either make it configurable so it can be switched off or change the message display in such a way that there is always space for a last blank line left in which the `... is typing` message can appear without moving previous text.

**Comment by seripap** [comment]
Sure thing, i've added it to the roadmap @ #5

**Comment by seripap** [comment]
The parent feature is being rewritten and currently doesn’t exist. When it comes back this portion will be built in.
