### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by zichaolim** [seripap/darkwire.io#36]
The steps I follow seem like not installing any products related to darkwire chat system. Please advise on this matter.

# Get latest version of NodeJS for ES2015 support
npm install -g n
n stable
npm install

# Starting dev environment
npm run dev

# Running tests locally
brew install chromedriver
npm test

# Start a local instance of darkwire
npm run bundle
npm start

# Changing ports, default is 3000
port=3000 npm start

**Comment by seripap** [comment]
What is your error?
