### ISSUE TITLE
dockerize it

### ISSUE THREAD

**Issue by geoder101** [seripap/darkwire.io#39]
Hello, I think what's missing from this fantastic project is support for docker, so as to be able to deploy the app anywhere and seamlessly.

For instance we should be able to:

__1) Build the image__

```bash
docker build -t darkwire .
```

__2) Optionally push it to our private registry__

```bash
docker tag darkwire private-registry/darkwire
docker push private-registry/darkwire
```

__3) And ultimately run the app (in the production host)__

```bash
docker run -d -p 3000:3000 private-registry/darkwire
```

I can send you a PR for a respective `Dockerfile` :)
What do you think?

**Comment by seripap** [comment]
Definitely, this is fairly simple enough. I will push up a dockerfile soon, thanks for the suggestion!

**Comment by geoder101** [comment]
Cool! So it's ok to close the issue.
As a side note, I'm leaving here a reference to a relative commit https://github.com/geoder101/darkwire.io/commit/4b1c376e0971bffb472421c1a07247a789035dbc

Thanks!
