### ISSUE TITLE
read upper-case `PORT` environment variable

### ISSUE THREAD

**Issue by geoder101** [seripap/darkwire.io#40]
To the best of my knowledge environment variable names are, by convention, in upper-case.
In addition, in some environments, such as in Heroku (the popular PaaS), the aforementioned convention [is followed](https://devcenter.heroku.com/articles/dynos#local-environment-variables).

I believe it would be better if this convention is followed.
The issue that arises though, should such a change be adopted, whether it is backward-compatible or not.

I suggest that it is backward-compatible.
Namely, this change would suffice:

```diff
diff --git a/src/app.js b/src/app.js
index 7d3193d..cbfeffc 100644
--- a/src/app.js
+++ b/src/app.js
@@ -11,7 +11,7 @@ import fs from 'fs';
 import Room from './room';

 const $CONFIG = {
-  port: process.env.port || 3000
+  port: process.env.port || process.env.PORT || 3000
 };

 const app = express();
```

Do you have any other considerations?

PS: _I have a PR ready, but I thought it would be better if I opened an issue first._

**Comment by seripap** [comment]
Sure thing, send a PR over. I know AWS requires the same format.
