### ISSUE TITLE
About anonymousity

### ISSUE THREAD

**Issue by Ashtor** [seripap/darkwire.io#43]
Please make it so you mask people's IP's so the IPs doesnt show to anyone no matter what,completely anonymous and encrypted (that means no logs whatsoever no matter what,no trace of IPs or of any kind,nothing is saved on the server,people can't see people's IPs or any info. people won't use the chat otherwise.
Second thing..
About the roomname that changes everytime you enter. please make it so people can name their room with their own roomname instead of just name that comes up randomly

**Comment by seripap** [comment]
There's no way we can completely mask your IP. 

We have no logs on our server of any of this and no logs on the server that can trace chat rooms or chat messages. All chat messages are stored on the client (you), the server is just there to transmit the messages. As for room name, i'll leave a comment in #44
