### ISSUE TITLE
expired certificate

### ISSUE THREAD

**Issue by SamClinckspoor** [seripap/darkwire.io#49]
Looks like https://darkwire.io has an expired certificate:

<img width="334" alt="screen shot 2017-04-03 at 16 36 46" src="https://cloud.githubusercontent.com/assets/158820/24614532/c6566ffa-188b-11e7-8014-292975478441.png">
Looks like you use letsencrypt with nginx, so an nginx reload might be enough to fix it if the certificate renewal happened without errors.

**Comment by seripap** [comment]
Thanks, in process of upgrading the server now; hold tight.

**Comment by seripap** [comment]
All good now, thanks for the report.
