### ISSUE TITLE
Updating to socket 2.0

### ISSUE THREAD

**Issue by SrPatinhas** [seripap/darkwire.io#51]
nice chat! Are you thinking on update socket.io to 2.0 for the next milestone?

**Comment by seripap** [comment]
It'll be a complete rewrite, making it more future proof and faster. coming soon-ish.

**Comment by SrPatinhas** [comment]
ok :p but do you have any timeline, even for a commit?

**Comment by seripap** [comment]
No timeline finalized yet but development will start soon. The setup is complete, it's just not added to this repo yet. Swing back in a few weeks 👍

**Comment by seripap** [comment]
Will be fixed in #26
