### ISSUE TITLE
Button to download

### ISSUE THREAD

**Issue by svetlanavassilia** [seripap/darkwire.io#60]
Hi.
It was easier to write when the button to download was at the right instead of left.
When we want to write, we click on the button by accident and it opens the download windows.
Please can you replace it at the extrem right ?

**Comment by seripap** [comment]
Fixed in latest release.

**Comment by svetlanavassilia** [comment]
Thank you 

--- 
Svetlana Vassilianova 
Mon profil Google plus : https://plus.google.com/103545618574873326448 
Emails alternatifs : svetlana.vassilianova@protonmail.ch / svetlana.vassilianova@tuta.io 


De: "Daniel Seripap" <notifications@github.com> 
À: "seripap/darkwire.io" <darkwire.io@noreply.github.com> 
Cc: "svetlanavassilia" <svetlana.vassilianova@unseen.is>, "Author" <author@noreply.github.com> 
Envoyé: Mardi 12 Décembre 2017 15:11:21 
Objet: Re: [seripap/darkwire.io] Button to download (#60) 



Fixed in latest release.
