### ISSUE TITLE
Encoding problems of € symbol

### ISSUE THREAD

**Issue by dietmarw** [seripap/darkwire.io#9]
When entering `€` then the recipient gets ` ¬`. There might be other symbols that don't work.

**Comment by dietmarw** [comment]
Typing `€` as HTML entity `&euro;` works fine btw.

**Comment by alanfriedman** [comment]
Interesting...we'll look into it.

**Comment by seripap** [comment]
Thanks for finding this- fix will be shipped with v1.5

**Comment by dietmarw** [comment]
Wow thanks. That was quick.

**Comment by alanfriedman** [comment]
@dietmarw @seripap Can we close this?

**Comment by alanfriedman** [comment]
Nevermind, it's not released yet. Let's wait.

**Comment by dietmarw** [comment]
Depends if you regard something as fixed once a "fixing" commit is done or when it is finally deployed/part of a tagged release. Most projects I know do the former. But it is really up to the project ;-)
